# Generated by Django 5.2.6 on 2025-09-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfunction',
            name='allowed_libraries',
            field=models.TextField(blank=True),
        ),
    ]
