# Generated by Django 5.2.6 on 2025-09-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_alter_testfunction_allowed_libraries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='testfunction',
            unique_together={('name', 'assignment')},
        ),
    ]
