name: Client CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'client-src/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'client-src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e client-src/.

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 client-src/src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 client-src/src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pip install pytest
        pytest client-src/tests
