name: Server CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'server-src/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'server-src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server-src/requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 server-src/AutoGrader server-src/grader --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 server-src/AutoGrader server-src/grader --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Django tests
      run: |
        python server-src/manage.py test server-src/grader
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DEBUG: True
        DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1'
        DATABASE_ENGINE: 'sqlite3'
        DATABASE_NAME: 'mydatabase'

    - name: Build Docker image
      run: docker build ./server-src -t autograder-server:latest
